### PR TITLE
Repocleanup

### PR DESCRIPTION
**Pull request by HacDan**
Removed `.DS_Store` files from the repo. They're in the `.gitignore`. No need to track them.

### CODE REVIEW

**Comment by Xonshiz** [comment]
Thanks for the cleanup, but please take latest and merge changes with your branch before sending PR. This one has merge conflicts which shouldn't be there because you're just removing `.DS_Store` files.

**Comment by HacDan** [comment]
@Xonshiz This was based against master and PR'd against Dev per the Contribution guidelines. I'm not sure why the build is failing, but I believe that's why there's a trail of commits above. 

Would you like me to rebase against Dev, 6 commits behind? 

I'll rebase the other PR either way as it's not dependant on this commit, obviously.

**Comment by Xonshiz** [comment]
Looks like dev was behind the master. Do one thing, for now, make a branch out of the current master with your username and push your changes in it. I'll clean up this `develop` branch later on.

**Comment by Xonshiz** [comment]
closing because builds will fail due to merge conflicts.

**Pull request closed without merging**
